# Generated by Django 4.1.3 on 2022-11-07 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=50)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('icon', models.URLField(blank=True, max_length=1028, null=True)),
                ('emailId', models.EmailField(blank=True, max_length=254, unique=True)),
                ('primaryContactNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('isMailVerified', models.BooleanField(default=False)),
                ('isPhoneVerified', models.BooleanField(default=False)),
                ('emailKey', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('otpGenTime', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('djangoUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='django_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
