# Generated by Django 4.1.3 on 2022-11-07 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('todays_price', models.FloatField(null=True)),
                ('offer_price', models.FloatField(null=True)),
                ('measuring_unit', models.CharField(choices=[('kg(s)', 'Kilograms'), ('l(s)', 'Literes'), ('c(s)', 'Count')], default='Kg(s)', max_length=100)),
                ('available_quantity', models.FloatField(null=True)),
                ('min_available_qty', models.FloatField(default=1.0)),
                ('max_available_qty', models.FloatField(default=models.FloatField(null=True), null=True)),
                ('max_qty_allowed_per_order', models.FloatField(default=0, null=True)),
                ('gst', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.retailer')),
            ],
        ),
    ]
